# Generated by Django 4.2.7 on 2023-12-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0005_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeID', models.IntegerField()),
                ('challengeTitle', models.CharField(max_length=25)),
                ('challengeContent', models.CharField(max_length=500)),
                ('challengeInstructions', models.CharField(max_length=500)),
                ('challengeConditions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzleID', models.IntegerField()),
                ('puzzleTitle', models.CharField(max_length=25)),
                ('puzzleContent', models.CharField(max_length=500)),
                ('puzzleInstructions', models.CharField(max_length=500)),
                ('puzzleConditions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Page', models.IntegerField()),
                ('Title', models.CharField(max_length=35)),
                ('Content', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='PyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeID', models.IntegerField()),
                ('challengeTitle', models.CharField(max_length=25)),
                ('challengeContent', models.CharField(max_length=500)),
                ('challengeInstructions', models.CharField(max_length=500)),
                ('challengeConditions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzleID', models.IntegerField()),
                ('puzzleTitle', models.CharField(max_length=25)),
                ('puzzleContent', models.CharField(max_length=500)),
                ('puzzleInstructions', models.CharField(max_length=500)),
                ('puzzleConditions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PyStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Page', models.IntegerField()),
                ('Title', models.CharField(max_length=35)),
                ('Content', models.CharField(max_length=1500)),
            ],
        ),
    ]
