# Generated by Django 4.2.7 on 2023-12-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0006_cchallenge_cpuzzle_cstory_pychallenge_pypuzzle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cchallenge',
            name='challengeConditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cchallenge',
            name='challengeContent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cchallenge',
            name='challengeInstructions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cpuzzle',
            name='puzzleConditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cpuzzle',
            name='puzzleContent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cpuzzle',
            name='puzzleInstructions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cstory',
            name='Content',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pypuzzle',
            name='puzzleConditions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pypuzzle',
            name='puzzleContent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pypuzzle',
            name='puzzleInstructions',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pystory',
            name='Content',
            field=models.CharField(max_length=2000),
        ),
    ]
