# Generated by Django 4.2.7 on 2023-12-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0007_alter_cchallenge_challengeconditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstory',
            name='Content',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='pystory',
            name='Content',
            field=models.CharField(max_length=2500),
        ),
    ]
