# Generated by Django 4.2.7 on 2023-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0008_alter_cstory_content_alter_pystory_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstory',
            name='Title',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='pystory',
            name='Title',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
