# Generated by Django 4.2.7 on 2023-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0009_alter_cstory_title_alter_pystory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cstory',
            name='Content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pystory',
            name='Content',
            field=models.TextField(),
        ),
    ]
