# Generated by Django 4.2.7 on 2023-12-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0010_alter_cstory_content_alter_pystory_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListTrial',
        ),
    ]
