# Generated by Django 4.2.7 on 2023-12-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetales_app', '0011_delete_listtrial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregistration',
            old_name='FullName',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='adminregistration',
            name='Email',
        ),
    ]
